ci:
  skip: [pylint]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: debug-statements
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.5.3"
    hooks:
      - id: ruff
        args: ["--fix"]
        exclude: "tests/input/"
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: [--safe, --line-length=120, "--exclude=pylint_django/tests/input/"]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ["-rn", "-sn", "--fail-on=I"]
        exclude: "tests/input/"
